# Server configuration
server.port=8080


# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tutorsys
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway migration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Spring Mail (Mock Configuration - redirect to console or configure for local dev)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=mock
spring.mail.password=mock
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# File Upload / Invoices Storage
tutorsys.invoices.dir=C:/Thiagu/DEVIN PROJECTS/TUTORSYS/invoices

# JWT Configuration
tutorsys.jwt.secret=84a51684c311147e0a4c58dfeb50c18259830f3a4b6f1200185e13d726b21650
tutorsys.jwt.expiration=86400000

# OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Enable Lombok log
logging.level.com.tutorsys=DEBUG
logging.level.org.springframework.security=TRACE
